### ISSUE TITLE
Show also newer related bookmarks? 

### ISSUE THREAD

**Issue by TheNomad11** [ilesinge/shaarli-related#13]
Is it possible to continuosly update the related bookmarks? For it seems that they always stay the same.

Example: Two years ago I posted a bookmark about shaarli plugins. Today, I post anonther one. When I click on my bookmark from two years ago, the most recent related post from today will not show up. It will only show related bookmarks that I posted two years ago and earlier.

I have no idea how hard this would be to implement, I suppose it is no easy task? Thanks!

**Comment by ilesinge** [comment]
Hi TheNomad11,
Can you verify that you have the most recent version of the plugin ? There has been a bug during a short period of time that may be related to what you describe : https://github.com/ilesinge/shaarli-related/issues/7 (it is fixed in the current version).
The related bookmarks associated to a specific bookmark are the ones that have the most similar tags. If there are multiple bookmarks to choose from with the same number of similar tags, they are randomized at every page load. There is currently no restriction on the age of the related bookmark, they could have been posted earlier or more recently than the currently shown bookmark.
For instance this bookmark has been posted in 2012: https://b.ndre.gr/shaare/s9iNxQ . You may see among the related bookmarks "Splitgraph", which have been posted in 2020.
If updating does not fix your problem, can you shoot me a link to your shaarli instance with a specific example ?

**Comment by TheNomad11** [comment]
Hi @ilesinge  thanks so much, that was the reason, now I got the newest version and am happy! Really great plugin, thanks so much!!
